//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Notes
    {
        public int ID { get; set; }
        public string Note_Desc { get; set; }
        public string Note_Manager { get; set; }
        public string Note_User { get; set; }
    }
}
