//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Projects
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDes { get; set; }
    }
}
