//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTaskTrackerEntities : DbContext
    {
        public DBTaskTrackerEntities()
            : base("name=DBTaskTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Users> TB_Users { get; set; }
        public virtual DbSet<TB_Projects> TB_Projects { get; set; }
        public virtual DbSet<TB_Tasks> TB_Tasks { get; set; }
        public virtual DbSet<TB_Notes> TB_Notes { get; set; }
    }
}
