using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using CS_project.PL;

namespace CS_project.PL
{
    public partial class USER : DevExpress.XtraEditors.XtraUserControl
    {
        // main var

        DBTaskTrackerEntities db;
        TB_Users Users;
        Form_User_add form_add;
        public int id;

        public USER()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CS_project.DBTaskTrackerEntities dbContext = new CS_project.DBTaskTrackerEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.TB_Users.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.TB_Users.Local.ToBindingList();
        }

        private void bot_add_Click(object sender, EventArgs e)
        {
            form_add = new Form_User_add();
            form_add.id = 0;
            form_add.bo_save_User.Text = "اضافة";
            form_add.ShowDialog();
        }

        private void bot_update_Click(object sender, EventArgs e)
        {
            UserUpdate();
        }
        //update data from database
        public void UserUpdate()
        {
            try
            {
                db = new DBTaskTrackerEntities();
                gridControl1.DataSource = db.TB_Users.ToList();
            }
            catch
            {
                MessageBox.Show("faild connection with database!", 
                    "there is connection error",
                    MessageBoxButtons.OK, 
                    MessageBoxIcon.Warning);
            }
        }

        private void bot_edit_Click(object sender, EventArgs e)
        {
            //هحدد اللي انا عايز اعدلها
            db = new DBTaskTrackerEntities();
            Users =new TB_Users();
            id = Convert.ToInt16(gridView1.GetFocusedRowCellValue("ID"));
            Users =db.TB_Users.Where(x=> x.ID == id).FirstOrDefault();
            //
            form_add = new Form_User_add();
            form_add.id = id;
            form_add.bo_save_User.Text = "تعديل";
            //
            form_add.txt_fullName.Text = Users.FullName;
            form_add.txt_pass.Text = Users.Password;
            form_add.txt_username.Text = Users.UserName;
            form_add.combo_role.SelectedItem = Users.State;
            //
            form_add.ShowDialog();


        }
    }
}
